- public/index.html
- src/components/taskbar/taskbar.scss
Small changes to website (og meta)
> Small changes

- src/components/start/index.js
- src/components/start/startmenu.scss
Made the app icon buttons in the startmenu be clickable in the whole icon area and made the app name text unselectable.
> Improved startmenu icons/buttons

- src/components/start/index.js
- src/components/start/searchpane.scss
- src/components/start/sidepane.scss
- src/index.css
> Some great fixes

- .github/workflows/can-docker-build.yml
- .github/workflows/main.yml
- Dockerfile
Hi I've added Docker support to the project via the Dockerfile. I have also added a GitHub action to auto generate the docker Images and publish them to GitHub packages.
> Docker Support

- README.md
Add command to show how to use with docker.
> Add docker command

- README.md
> fix misspelled word

- src/containers/applications/apps/edge.js
in input there should be "value" prop not "defaultValue" prop
> Solved - issue in edge browser when clicking on google icon

- src/containers/applications/apps/edge.js
Reverts blueedgetechno/windows11#128
> Revert "Solved - issue in edge browser when clicking on google icon"

- src/components/start/index.js
- src/components/start/sidepane.scss
Fixed some inconsistency between different browsers in the sliders of the action center.
Example : Before(left) , After(right) on Edge browser
> fixed action center's sliders inconsisteny

- public/404.html
Shouldn't we send them to issues when there is a problem?
> update 404 page

- src/components/menu/menu.scss
- src/components/start/sidepane.scss
- src/components/taskbar/taskbar.scss
- src/containers/applications/tabs.scss
- src/containers/background/back.scss
You can merge now @blueedgetechno
> Animation updates

- package-lock.json
- src/containers/applications/apps/calculator.js
- src/containers/applications/tabs2.scss
- src/containers/applications/wnapp.scss
> dark-mode : Calculator

- public/dycalendar.css
- src/components/start/searchpane.scss
- src/components/start/sidepane.scss
- src/components/taskbar/index.js
- src/components/taskbar/taskbar.scss
- src/containers/applications/wnapp.scss
- src/index.css
|![image](https://user-images.githubusercontent.com/89068816/140402637-01504d5c-9f83-4c36-b3bb-1e7fd5bc9d81.png)|![image](https://user-images.githubusercontent.com/89068816/140460610-46e6d10e-2a1c-4c81-96ed-1f18b29de51b.png)|
|---|---|
| Action Center | Calendar|
> dark-mode : Action Center & Calendar :)

- src/components/start/searchpane.scss
- src/components/start/start.js
- src/components/start/startmenu.scss
- src/components/taskbar/taskbar.scss
> dark-mode : Start & Search menu :)

- src/components/start/sidepane.scss
- src/containers/applications/apps/about.js
- src/containers/applications/tabs2.scss
|![image](https://user-images.githubusercontent.com/89068816/140634284-ffc55b0b-d7c2-4c98-8983-0180bf3857fc.png)|![image](https://user-images.githubusercontent.com/89068816/140634418-11df412e-7197-4a8c-92cc-f874cd50659d.png)| |
|-|-|-|
| about | widgets | browser (soon)|
> dark-mode : finale :)

- src/containers/applications/tabs2.scss
https://user-images.githubusercontent.com/89068816/142589429-3d0e1fd0-1c89-4478-a743-0aec6a8402c9.mp4
> Fix : glitchy resizing of calculator

- src/components/start/startmenu.scss
- src/components/taskbar/taskbar.scss
- src/containers/applications/tabs.scss
- src/utils/general.scss
https://user-images.githubusercontent.com/89068816/142856608-a804d3eb-a60c-4441-bd1a-f14a5a6c636a.mp4
these were fixed :)
also fixed scrollbars in some apps like store being unusable (it tries to resize the app instead)
> Few minor fixes : )

- src/components/menu/menu.scss
- src/components/start/index.js
- src/components/start/searchpane.scss
- src/components/start/sidepane.scss
- src/components/start/start.js
- src/components/start/startmenu.scss
- src/components/taskbar/Battery.js
- src/components/taskbar/index.js
- src/components/taskbar/taskbar.scss
- src/containers/applications/apps/assets/store.scss
- src/containers/applications/apps/notepad.js
- src/containers/applications/tabs.scss
- src/containers/applications/tabs2.scss
- src/containers/applications/wnapp.scss
- src/containers/background/back.scss
- src/containers/background/index.js
- src/index.css
- src/reducers/sidepane.js
- src/utils/general.scss
> dark-mode : Notepad , update startMenu , "Sign in" button lockScreen , few fixes & changes

- src/utils/apps.js
Excel was being shown twice because of it being added in the store
Thanks oliverGamez#8266 for bringing this issue to notice
> fix duplicate excel

- src/components/start/start.js
- src/containers/applications/apps/edge.js
- src/reducers/apps.js
> Added Info about IFrame: Refused to connect

- src/reducers/news.json
> Grammar fixes.

- src/components/start/start.js
- src/components/start/startmenu.scss
- src/containers/applications/apps/settings.js
- src/containers/applications/index.js
- src/containers/applications/wnapp.scss
- src/containers/background/back.scss
- src/containers/background/index.js
- src/utils/apps.js
- src/utils/index.js
updated boot screen loader to be clockwise, slighly smaller
start menu more responsive
now clicking on the recommended apps in the start menu works
: )
> few small fixes :)

- src/components/start/start.js
- src/components/start/startmenu.scss
- src/components/start/widget.js
- src/containers/applications/apps/assets/spotify.scss
- src/containers/applications/apps/calculator.js
- src/containers/applications/apps/explorer.js
- src/containers/applications/apps/notepad.js
- src/containers/applications/apps/spotify.js
- src/containers/applications/apps/store.js
- src/containers/applications/apps/terminal.js
- src/containers/applications/wnapp.scss
- src/index.css
- src/utils/general.scss
> updated scrollBars to look like win11 :)

- public/dycalendar.css
- public/dycalendar.js
- src/components/start/searchpane.scss
- src/containers/applications/wnapp.scss
now it looks lil bit more like win11 : )
| ![image](https://user-images.githubusercontent.com/89068816/149728000-adddcd52-b49e-4536-8523-70426653986e.png) |  ![image](https://user-images.githubusercontent.com/89068816/149728051-1a7853a6-4155-46ea-9cff-e800a2661d93.png) | ![image](https://user-images.githubusercontent.com/89068816/149728796-97802c4e-ad96-4bb1-8f71-3336de80cfa5.png) |
|---|---|---|
| before | real | updated |
> updated calendar : )

- src/containers/applications/apps/spotify.js
- src/containers/applications/wnapp.scss
- src/index.css
- src/utils/general.scss
> fix horizontal scrollbar :)

- src/containers/applications/apps/terminal.js
> Add eval command

- .github/workflows/desktop.yml
- .github/workflows/windows.yml
- src-tauri/tauri.conf.json
> Enable signing

- src/components/start/sidepane.scss
- src/components/start/startmenu.scss
- src/containers/applications/tabs.scss
Make motions in Windows11 more realistic by improving the `transition` property.
> Bring motion closer to the real thing

- README.md
- src/containers/applications/apps/discord.js
> Fix discord links

- src/containers/applications/draft.js
> Add camera support to iframe

- .github/workflows/deploy-preview.yml
- .github/workflows/gen-preview.yml
> new preview system

- src/containers/background/index.js
- src/utils/general.js
> Fix pictures for non root domain

- public/locales/en/translate.json
- src/containers/applications/apps/about.js
Adds support for multiple languages
> MULTILANG ABOUT APP

- public/locales/en/translate.json
- src/containers/applications/apps/store.js
> Start store translations

- src/components/start/index.js
- src/components/start/sidepane.scss
> collapseable calendar

- src/containers/applications/apps/assets/settings.scss
- src/containers/applications/apps/assets/settingsData.json
- src/containers/applications/apps/settings.js
- yarn.lock
> language switcher in settings

- src/containers/applications/apps/assets/settings.scss
- src/containers/applications/apps/settings.js
> settings nav indicator animation update

- src/index.js
> add issue feedback

- src/containers/applications/draft.js
> Andrew pr 95

- public/locales/en/translate.json
- src/containers/applications/apps/camera.js
Add translation support to camera app
> Add translation support to camera

- src/containers/applications/apps/assets/settings.scss
- src/containers/applications/apps/assets/taskmanager.scss
- src/containers/applications/apps/settings.js
- src/containers/applications/apps/taskmanager.js
- src/containers/applications/wnapp.scss
- src/reducers/apps.js
> task manager

- src/App.js
- src/App.js.bak
- src/components/menu/index.js
- src/components/start/index.js
- src/components/start/start.js
- src/components/start/widget.js
- src/components/taskbar/index.js
- src/containers/applications/apps/about.js
- src/containers/applications/apps/assets/jiosaavn.js
- src/containers/applications/apps/calculator.js
- src/containers/applications/apps/explorer.js
- src/containers/applications/apps/notepad.js
- src/containers/applications/apps/settings.js
- src/containers/applications/apps/store.js
- src/containers/background/index.js
- src/reducers/apps.js
- src/reducers/menu.js
- src/reducers/sidepane.js
- src/reducers/taskbar.js
- src/reducers/wallpaper.js
- src/utils/bin.js
- src/utils/index.js
reverted 1c9a899e37cbdfc07f03400e88c7cdbec1166e7a
> fix #413 right click menu bug

- public/locales/en/translate.json
- src/containers/applications/apps/getstarted.js
Add translation support to OOBE
> START TRANSLATION OF OOBE

- src/containers/applications/apps/assets/getstarted.scss
- src/containers/applications/apps/getstarted.js
- src/containers/applications/wnapp.scss
> darkmode OOBE

- .github/workflows/package-lock.yml
- craco.config.js
- package-lock.json
- package.json
Me putting a v8 engine into react
> Speed up Builds

- .firebaserc
- .github/workflows/PR-Preview.yml
- craco.config.js
- firebase.json
- package-lock.json
- package.json
- src/index.js
User login and personalisation update
> start of Save system

- src/containers/applications/apps/assets/settingsData.json
Correct typographical errors and mistakes in grammar, style, and spelling in settingsData.json
Fixes #605
> settingsData.json proofreading edits

- .github/workflows/Build-Deploy.yml
Waiting for @blueedgetechno to change the source to Github Actions in https://github.com/blueedgetechno/win11React/settings/pages
this save us around 40s in deployment
> gh-pages new custom actions

- src/utils/general.jsx
mouseDown on the modal title ,there has no any action
> bugfix: drag error

- .github/workflows/Issue-text.yml
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes [failing GitHub Workflow due to missing checkout](https://github.com/blueedgetechno/win11React/actions/runs/3021983182):
GitHub Action `stefanbuck/github-issue-parser@v2` is trying to access an issue template that is not accessible before checkout. This error resolves in missing labels on created issues.
> fix(ci): Add missing checkout

- index.html
Remove all the commented stuff because we don't use them (at least for now)
> Remove unneeded stuff

- src/containers/applications/apps/assets/settings.scss
> fixed font color and weight in setting search bar

- pnpm-lock.yaml
- src/components/start/searchpane.scss
- src/components/start/start.jsx
- src/i18nextConf.js
- src/index.css
- src/index.jsx
- src/reducers/dir.json
- src/reducers/widpane.js
- src/utils/apps.js
- src/utils/bin.js
- src/utils/general.jsx
- src/utils/general.scss
- src/utils/index.js
- Fixes #664
- Improves code
- Improved `<Suspense>`
> ♻️ Fix issue and refactor

- src/containers/applications/apps/terminal.jsx
- src/containers/applications/tabs.scss
Improved the terminal: added color command
Related to #669 (issue)
New feature (non-breaking change which adds functionality)
> terminal color command

- src/containers/applications/apps/assets/getstarted.scss
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes # (issue)
> corrected the overflow in get started window

- src/containers/applications/apps/assets/settingsData.json
This PR adds the correct icons to more of the setting items. Only a few more icons are still missing.
This PR advances progress on issue #339.
> add icons to more settings

- src/containers/applications/apps/assets/settings.scss
- src/containers/applications/apps/settings.jsx
The settings app is now responsive (for browsers that [support container queries](https://caniuse.com/css-container-queries)).
also the msft logo not showing was fixed.
> Responsive settings via container queries :)

- src/containers/applications/apps/store.jsx
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes # (issue)
> Add custom store function

- README.md
I want to be on the contributors too uwu :p
> Added stuff about sharing terms

- src/containers/applications/apps/terminal.jsx
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes # (issue)
#386 
Added support for ipconfig like command
> Added ipconfig Command

- .github/workflows/deploy.yml
- src/reducers/wallpaper.js
> fix:wallpaper keeps resetting #284

- src/utils/apps.js
Change the utils of Desktop is type and action
Utils/apps.js
[ ] Bug fix (non-breaking change which fixes an issue)
> Fix the Blue in Desktop

- src/actions/index.js
- src/reducers/settings.js
- src/reducers/sidepane.js
Now, when you enable Airplane mode, it will automatically disable Wi-Fi and Bluetooth if they were previously enabled.
Fixes #801 
> Fixed: Wi-Fi and Bluetooth toggling when flight mode is enabled.
